### ISSUE TITLE
关于头部和底部组件的问题

### ISSUE THREAD

**Issue by wenkangzhou** [naivehhr/react-native-refreshflatlist#10]
我看代码ListHeaderComponent被用于显示刷新的UI，但如果我们的业务需要用到FlatList的ListHeaderComponent，是不是就没办法了，可否把刷新的UI抛离出来，尽量保持不改变FlatList原有的属性。

**Comment by naivehhr** [comment]
Hello，多谢提的建议。最近太忙没有时间尝试更改…您可以fork一下做些修改，欢迎提PR:smiley:
