### ISSUE TITLE
in this environment the sources for assign must be an object

### ISSUE THREAD

**Issue by ddwhan0123** [naivehhr/react-native-refreshflatlist#2]
![2017-06-27 02 12 40](https://user-images.githubusercontent.com/9019351/27553612-2fae5e56-5ade-11e7-89cb-c5b48c038ebc.png)
react-native: 0.43.4
platform:iOS

出错地点:445行
<img width="786" alt="2017-06-27 02 14 17" src="https://user-images.githubusercontent.com/9019351/27553652-5cd72598-5ade-11e7-8c53-0d88dd6c4588.png">

**Comment by naivehhr** [comment]
感谢反馈~
我本地未重新此问题，方便看下调用的代码吗？
ps: 可先测试example是否运行正常。

**Comment by ddwhan0123** [comment]
@naivehhr 你好，查出问题了，只要往控件里传css样式报错。
然后android FlatList 华为真机特别卡，跑demo也卡

**Comment by naivehhr** [comment]
@ddwhan0123 
你可以试试下面传入css的方式；如果要控制RefreshFlatList大小可以设置外层View的样式；
麻烦请提供下华为手机的系统版本吧；
ps: android上是没有ios上流畅的，但也在可接受范围以内，我正在着手优化android模块，如果你有idea欢迎沟通交流:)
```
render() {
    return (
      <View style={styles.container}>
        <RefreshFlatList
          data={this.state._data}
          renderItem={this._renderItem}
          viewType={'ListView'}
          style={{backgroundColor: 'red'}}
        />
      </View>
    );
  }
```

**Comment by naivehhr** [comment]
@ddwhan0123 android真机调试时候确实有问题，release包情况会好很多。

**Comment by ddwhan0123** [comment]
@naivehhr FlatList页面复杂的情况下就算预加载一个item
减少pulltorefresh触发率还是很卡。
机型:华为p10

**Comment by naivehhr** [comment]
@ddwhan0123 还是真机调试吗？用模拟器试试呢~
这个apk你直接安装到手机上试试，看下效果
[app-release.apk.zip](https://github.com/naivehhr/react-native-refreshflatlist/files/1107632/app-release.apk.zip)

**Comment by ddwhan0123** [comment]
@naivehhr 模拟器跑你的 demo用真机跑你的demo都还好，实际项目就卡的不行（当然本身页面比较复杂）

**Comment by naivehhr** [comment]
@ddwhan0123 QQ 1903283729

**Comment by ddwhan0123** [comment]
@naivehhr 加了 qq

**Comment by naivehhr** [comment]
问题已解决。
