### ISSUE TITLE
安卓端无法下拉,不能点击

### ISSUE THREAD

**Issue by GreyLove** [naivehhr/react-native-refreshflatlist#3]
安卓端无法下拉,不能点击,ListFooterComponent设置后无效

**Comment by naivehhr** [comment]
@GreyLove example 能正常运行吗？组件link了没？
已经修改README中ListFooterComponent => listFooterComponent :-D

**Comment by GreyLove** [comment]
@naivehhr 感谢回复! listFooterComponent已解决,已link,但安卓端不能下拉

**Comment by naivehhr** [comment]
@GreyLove 示例项目android能下拉么？代码贴上来看看

**Comment by GreyLove** [comment]
render() {
        const {listData, loading, refreshing} = this.listStore;
        console.log(refreshing, loading, listData);


        return (
            <View style={styles.containStyle}>
                <RefreshFlatList
                  data={listData.slice()}
                  refreshing={refreshing}
                  onRefreshFun={() => this._onRefresh()}
                  onEndReached={this._onEndReached()}
                  customRefreshView={this._customerHeader}
                  listFooterComponent={this._renderFooter}
                  renderItem={this._renderItem}
                  ItemSeparatorComponent={() => this._ItemSeparatorComponent()}
                  viewType={ViewType.ListView}

                />
                <Loading isShow={loading}/>
            </View>
        );
    }
安卓示例可以下拉 react-native link react-native-refreshflatlist  这个link 是不是 有不对的地方

**Comment by naivehhr** [comment]
@GreyLove 界面上是不是有个红边？

**Comment by GreyLove** [comment]
@naivehhr  是的

**Comment by naivehhr** [comment]
@GreyLove 那就是没有link上，你手动配置下吧。
/android/settings.gradle
```
include ':react-native-refreshflatlist'
project(':react-native-refreshflatlist').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-refreshflatlist/android')
```
/android/app/
```
dependencies {
    compile project(':react-native-refreshflatlist')
    ....
}
```
MainApplication.java
```
import com.reactnativecomponent.swiperefreshlayout.RCTSwipeRefreshLayoutPackage;

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
             ...
            new RCTSwipeRefreshLayoutPackage()
      );
    }
```

**Comment by GreyLove** [comment]
@naivehhr 已解决,多谢
