### ISSUE TITLE
多次触发releaseToRefresh回调,而且没松手就执行了回调方法

### ISSUE THREAD

**Issue by lizhuoyuan** [naivehhr/react-native-refreshflatlist#4]
case RefreshState.releaseToRefresh:
                if (Platform.OS === 'ios' && flatposition < 0) {
                    //在这里可以做跳转事件
                    if (toTop && topimg.destinationUrl) {
                        RouteManager.routeJump({
                            page: routeConfig.WebView,
                            openType: 'present',
                            param: {url: topimg.destinationUrl},
                            fromRNPage: routeConfig.Home,
                        }, (event) => {
                            this._getData();
                        });
                    } else {
                        this._getData();
                    }
                } else if (Platform.OS === 'android' && flatposition === 0 && jumpflag) {
                    //在这里可以做跳转事件
                    if (toTop && topimg.destinationUrl) {
                        RouteManager.routeJump({
                            page: routeConfig.WebView,
                            openType: 'present',
                            param: {url: topimg.destinationUrl},
                            fromRNPage: routeConfig.Home,
                        }, (event) => {
                            this._getData();
                        });
                    } else {
                        this._getData();
                    }

                }

部分代码如上,使用过程中发现多次触发releaseToRefresh里面的内容(我已经加了判断来只执行一次),但是我希望在下拉松手之后才执行一个方法,请问有什么方式吗?

**Comment by naivehhr** [comment]
@lizhuoyuan 是会多次触发的。刷新的回调方法是onRefreshFun；比如： onRefreshFun={()=>console.log('触发刷新')}
![1](https://user-images.githubusercontent.com/5243456/29177655-d13c31c4-7e21-11e7-8b50-5ef77b16fae0.gif)

**Comment by lizhuoyuan** [comment]
谢谢,上午刚搞好 ,下午就看到你的回复,非常感谢.
竟然忘记了下拉刷新的方法~

**Comment by naivehhr** [comment]
👍 👍
