### ISSUE TITLE
Item中放入Swiper无法显示内容---android

### ISSUE THREAD

**Issue by lizhuoyuan** [naivehhr/react-native-refreshflatlist#5]
我在Flatlist中正常,
替换为Refreshflatlist之后 swiper中的内容不会显示:
![Uploading image.png…]()
ios 可以

**Comment by naivehhr** [comment]
@lizhuoyuan 
我直接在FlatList中使用swiper也显示不出来...看到你在swiper组件的issues中有解决这个问题[#525](https://github.com/leecade/react-native-swiper/issues/525),请问是怎么解决的呢？
![1](https://user-images.githubusercontent.com/5243456/29468175-c01f603c-8475-11e7-96db-fba5c97a1e66.gif)

**Comment by lizhuoyuan** [comment]
@naivehhr  swiper 的高度和宽度不在style里，而是作为swiper的属性出现的
你可以 直接给它设置高度和宽度， 例如:
<Swiper 
height={100}>

**Comment by lizhuoyuan** [comment]
<Swiper height={200}

**Comment by naivehhr** [comment]
@lizhuoyuan 恩的，设置removeClippedSubviews={false} android平台就可以了
```
_renderItem = () => {
    return (
      <View style={{ flex: 1}}>
        <Swiper style={{ height: 200}} >
          <View style={styles.slide1}>
            <Text style={styles.text}>Hello Swiper</Text>
          </View>
          <View style={styles.slide2}>
            <Text style={styles.text}>Beautiful</Text>
          </View>
          <View style={styles.slide3}>
            <Text style={styles.text}>And simple</Text>
          </View>
        </Swiper>
      </View>
    )
  }

  render() {
    return (
      <View style={{ flex: 1 }} >
        <RefreshFlatList
          viewType={'ScrollView'}
          renderItem={this._renderItem}
          removeClippedSubviews={false}
        />
      </View>
    );
  }
```
![1](https://user-images.githubusercontent.com/5243456/29486860-49cd1322-8522-11e7-976b-b242a528a398.gif)

此外还有个问题就是Swiper 设置 showsButtons={true} 时，触发刷新后两边的按钮位置会变动到屏幕中间...这个问题我还没什么思路，如果你有啥见解欢迎一起讨论🙂

**Comment by lizhuoyuan** [comment]
@naivehhr  抱歉... 没有显示过那个按钮

**Comment by naivehhr** [comment]
@lizhuoyuan 恩，没事，一般用不到，最近比较忙，后面有空我再查查问题

**Comment by lizhuoyuan** [comment]
@naivehhr  对了,刚好遇到个问题,  我的onRefreshFun只有打开调试模式时候才会执行 , 有遇到过吗

**Comment by naivehhr** [comment]
@lizhuoyuan IOS吗？我刚看了下Android，没这问题
