### ISSUE TITLE
onRefreshFun只在debug模式下才执行...

### ISSUE THREAD

**Issue by lizhuoyuan** [naivehhr/react-native-refreshflatlist#6]

**Comment by lizhuoyuan** [comment]
<RefreshFlatList
                        key={keyIndex}
                        ListFooterComponent={this._foot}
                        style={{backgroundColor: Colors.background_grey}}
                        refreshing={this.state.isRefreshing}
                        viewType={ViewType.ListView}
                        ref="vipNeedScroll"
                        renderItem={this._renderItemComponent}
                        customRefreshView={this._customerHeader}
                        showsVerticalScrollIndicator={false}
                        data={[{key: 1}, {key: 2}, {key: 3}, {key: 4}]}
                        extraData={this.state}
                        contentOffsetY={this.contentOffsetY}
                        onScroll={this.onScroll.bind(this)}
                        // style={styles.container}
                        //onEndReached={this._getMore}
                        //onEndReachedThreshold={0.1}
                        onRefreshFun={() => {
                            if (this.titleBar && Platform.OS === 'android') {
                                this.titleBar.setNativeProps({
                                    style: {opacity: 0}
                                });
                            }
                            this.setState({
                                isRefreshing: true
                            }, () => {
                                this._getData();
                                alert('1')
                            })
                        }}
                    />

只有打开调试模式时候 才会执行里面的方法,求帮助

**Comment by naivehhr** [comment]
@lizhuoyuan IOS吗？我刚看了下Android，没这问题

**Comment by lizhuoyuan** [comment]
@naivehhr  ios的

**Comment by naivehhr** [comment]
@lizhuoyuan ios的我抓包看了，没遇到这个问题...不应该存在这个问题因为release和debug包~~
此外 onScroll={this.onScroll.bind(this)} 这个组件中并未设置回调，你需要改下源码。

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/29505343-55baeb76-8678-11e7-82a0-5c73df6ac071.png)
并非是release和debug包的事
,而是debug remote js 模式开启才有效,不开就不触发,这久很尴尬,导致我没办法通过调试模式查找问题.
此外,onscroll我已经修改过源码,难道是我有哪里改错了?

**Comment by naivehhr** [comment]
@lizhuoyuan 你先回退下更改试试，我这是否debug remote js都没这问题的

**Comment by lizhuoyuan** [comment]
好吧,好像是我操作的问题,
下拉的时候,鼠标超出模拟器范围导致的头部回弹好像是触发的取消方法 ....
但我马上还要给你提个问题..

**Comment by lizhuoyuan** [comment]
![1](https://user-images.githubusercontent.com/15923901/29505684-42d51b9c-867a-11e7-8139-27de2df59bf7.gif)
会不停的在refreshing和releaseToRefresh 不停地切换

**Comment by lizhuoyuan** [comment]
不知道是不是又是我哪里改错了.. 尴尬

**Comment by naivehhr** [comment]
@lizhuoyuan 这个问题之前有么 QQ1903283729
