### ISSUE TITLE
下拉的时候拉到一半，然后手动复位列表，执行了列表条目的点击事件

### ISSUE THREAD

**Issue by thiswhy** [naivehhr/react-native-refreshflatlist#7]
下拉的时候拉到一半，然后手动复位列表，不执行刷新效果，但是执行了列表条目的点击事件，这个问题怎么破

**Comment by naivehhr** [comment]
@thiswhy IOS还是ANDROID？RN哪个版本呢？

**Comment by thiswhy** [comment]
android RN0.45.0 。我看你源码，在IOS里面已经写了个手势，然后我想在android拦截一下这个手势。希望你能做一个合理的处理，谢谢大神

**Comment by naivehhr** [comment]
由于PanResponder在Android上的兼容有问题，Android版本上并未使用PanResponder来实现，建议你也不要用😀

**Comment by thiswhy** [comment]
我这一口老血呀。。。。我就想在滑动的时候屏蔽掉列表的点击事件，不然拖动完了，手指还在当前的Item上面，还是会执行点击事件跳转到下一页。

**Comment by naivehhr** [comment]
明白了😂

**Comment by thiswhy** [comment]
哥们这个问题好解决吗？我是实在治不了了。我给他加了个手势可以屏蔽这个问题，但是点开下一页无法展示页面，好蛋疼。就好像state状态set不进去一样。疼~~~~

**Comment by naivehhr** [comment]
刚试了试一个方案，模拟器上ok但真机上有问题，我再看看有其他方案不。

**Comment by thiswhy** [comment]
对，我也试过了，模拟器运行好好的，真机就是有问题，弄了一下午了。。。。

**Comment by naivehhr** [comment]
升级到1.1.3。调用isTriggerPressFn方法，具体查看example。(暂时解决方案)
